### ISSUE TITLE
Duplicate Apps/Corrupt data as of 10/27?

### ISSUE THREAD

**Issue by taberrr** [omz/AppSales-Mobile#276]
Is it just me or did something change with the data being pulled down today?

After refreshing this morning, the app is giving incorrect sales amounts for the past several days, different amounts than before I refreshed. The "All Apps" button seems to be a reasonable amount, but it doesn't match the amount on the column in the bar graph. The app seems to have also reset/lost my color settings.

**Comment by ddaddy** [comment]
Same here. Not had a chance to look at what's happened. I was going to reinstall from scratch and see what gives.

**Comment by Morpheus2002** [comment]
I think I got the same issue. For me all apps and IAPs are duplicated, so I got 2 times more data. For some reason AppSales added all apps again.

**Comment by taberrr** [comment]
I was going to give re-installing a try too. I remember back in March there were some issues with CurrencyManager, maybe something changed there.

@Morpheus2002 you're right, it looks like the graph columns are *almost* double the button amounts, give or take a few.

**Comment by Morpheus2002** [comment]
@taberrr if you got to  *Account -> Manage Apps* you will see, that all apps are duplicated. 
If I try to *hide in dashboard* one duplicate, the other app becomes hidden too.

**Comment by taberrr** [comment]
@Morpheus2002 Ah yeah, I'm seeing that too.

**Comment by taberrr** [comment]
Deleting the account and re-adding doesn't seem to fix.

**Comment by omz** [comment]
Same here. Looking at the CSV, it looks like today's report contains new product type identifiers – I see "3F" and "3T", which haven't been in any previous report, as far as I can see. Not sure what those mean.

It looks like the same app is listed with multiple different product type identifiers, which is likely the reason duplicate products are added... If I remember correctly, AppSales uses the product type identifier for uniquing (might not be such a good idea, should probably use the SKU instead).

Btw, you can view the original file of a report by tapping its bar in the chart, and then selecting "CSV" at the bottom.

**Comment by taberrr** [comment]
@omz wow I never realized the CSV button was there, thanks for that! No idea what those type identifiers mean either, but I'm guessing it has something to do with AppleTV approaching release.

**Comment by omz** [comment]
Yeah, probably. They aren't listed here yet: http://help.apple.com/itc/appssalesandtrends/#/itc0c699d615

**Comment by Morpheus2002** [comment]
I suppose the new product types are for tvOS apps coming this Friday.

**Comment by omz** [comment]
Hmm, but why would they show up in my reports? I don't have any tvOS apps...

**Comment by ddaddy** [comment]
I don't think they are tvOS related as I have lots of them with `developer proceeds` and there's no way my apps would be on the tvOS App Store.

**Comment by Morpheus2002** [comment]
Ok. How do we fix this issue? It breaks all the stats. 😞

**Comment by ddaddy** [comment]
We wait until we find out what exactly 3F and 3T is meant to be.

**Comment by paulfowler** [comment]
I have a workaround. Although the meaning of 3F and 3T codes are presently unknown, they are not the cause of the duplication.
For some reason the productSKU sometimes has a trailing space before the tab delimiter. This is used as a primary key into the list of products, so causes a duplicate product to be created in the import. But with the same productID so it assumes the full purchase history.
My fix - i am no git hub expert so won't be doing a fork an pull request... but here is how to fix.
First do a full export of your reports incase something goes wrong, and pull off the ZIP via iTunes.
---
in Report.m method +insertNewReportWithCSV:inAccount: where productSKU is extracted. strip the trailing space. And if you can find a product with the productSKU with a space delete it (this does not delete the history, as the proper product is still referencing the productID history.

// existing line
		if (!productSKU) productSKU = [rowDictionary objectForKey:kReportColumnSKU2];
// extra lines
		if ([productSKU hasSuffix:@" "])
		{ // bug in 26th October reports, sku has trailing space
			Product *product = [productsBySKU objectForKey:productSKU];
			if (product)
				[moc deleteObject:product]; // clean up the mess
			int len = (int)productSKU.length;
			productSKU = [productSKU substringToIndex:len-1]; // fix SKU
		}
// end of fix

Now run the app and delete 26th, long press on the 26th oct, then tap delete., then check for new reports to re-import 26th. repeat for 27th, 28th etc until all your duplicated apps are gone, leaving you with you original correct apps, and correct colours.
then remove the if product mic delete lines - they have done their job.

Regards,
Paul.

**Comment by taberrr** [comment]
Awesome Paul! I created a PR with this: https://github.com/omz/AppSales-Mobile/pull/277

**Comment by omz** [comment]
Thanks!

**Comment by jasondmichaelson** [comment]
And today we have definitions for the codes:

3
Redownload
Redownload (iOS and tvOS), excluding iPad-only
3F
Redownload
Universal (iOS), excluding tvOS
3T
Redownload
iPad-only app
F3
Redownload
Mac app
