### ISSUE TITLE
"The application does not have a valid signature"

### ISSUE THREAD

**Issue by HemiMG** [omz/AppSales-Mobile#57]
I'm getting the error in the title when I try to build and install the latest version. I have my certificates and and provisioning profiles all in order. The error is also different from the one when a certificate or provisioning profile is incorrect. In searching the web for the problem, the most common (there are only 2 google pages of results) is that the Resources folder contains a subfolder named resources, or a duplicate file. Neither one of these seems to be the case in AppSales-Mobile. Has anyone else experienced this?
The app will compile and install on the iPod fine, but then it crashes after displaying the background image (and no other UI elements) for a few seconds. It is when I try to run it a second (or any subsequent) time that I get the error popping up in XCode, and the XCode Organizer. 
My certificates and profiles are definitely fine because they've worked flawlessly on previous version and neither of them have expired yet. It's pretty frustrating to have a problem that even Google has so limited info on.

**Comment by beforeold** [comment]
Unbelivable, I ran into this issue too, but still stuck.

**Comment by rsnitsch** [comment]
You can get a more detailed error message in the device log. In XCode: Window -> Devices -> Select your device -> At the bottom there is an error log with detailed information.

For example in my case it outputs something like this:
Failed to install application at file:///var/mobile/Media/PublicStaging ... : Error Domain=LaunchServicesError Code=0 "(null)" UserInfo={Error=ApplicationVerificationFailed, ErrorDetail=-402620391, ErrorDescription=Failed to verify code signature of /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.iKT2NH/extracted/XYZ.app/Frameworks/Raygun4iOS.framework : 0xe8008019 (The application does not have a valid signature.)}
